### ISSUE TITLE
Add a pane in the 'tmuxed' TidalVim window

### ISSUE THREAD

**Issue by gilfuser** [munshkr/vim-tidal#19]
Hi
First of all, thank you for this plugin. I'm learning vim through it and for it. And I think that soon I'll could live-code much faster and in more interesting ways that I was before.
I'm trying to split the window with TidalVim, to have a cheat-sheet, the snippets I'm doing, or something else. But when I do it, the vim pane will send the Haskell code to the new manually added pane, instead of to the GHCI pane.
I took a look at the tidalvim file in the bin folder, but I don't know Tmux well enough to understand what should I do there.
Do you know how could I make a new pane not interfere with the communication between the original ones?

bests,
Gil

**Comment by munshkr** [comment]
You can customize the *target pane*, which is the pane where GHCI will be, so that Vim knows where to send the lines. Just type the command `:TidalConfig` and it will ask you where the pane is. In the [README](https://github.com/munshkr/vim-tidal#tmux-target) there's a short explanation of how panes and windows work in tmux, but if you still can't get it to work send a screenshot of your current layout and I'll help you!
